import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
  Text,
  Flex,
  Box,
  Button,
  Input,
  Grid
} from "@chakra-ui/core";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box as="div" className={styles.header}>
          <Text className={styles.titletext}>
            <Text color="green" display="inline">Free</Text> Financial Freedom Webinar
          </Text>
          <Text marginTop={["45px", "60px", "75px", "90px"]} fontWeight="500" fontSize={["13px","20px", "27px", "33px"]} className={styles.text}>
            Are you tired of feeling uncertain or stressed about your financial future?
          </Text>
          <Text marginTop={["6px", "12px", "19px", "26px"]} fontWeight="300" fontSize={["12px", "17px", "22px", "27px"]} className={styles.text}>
            We are here to help you demystify the financial planning process and empower you to make wise money-related choices in your life. Peace of mind is just around the corner.
          </Text>
          <Text fontWeight="400" fontSize={["12px", "17px", "22px", "27px"]} className={styles.text}>
            Take your first step by participating in our Financial Freedom Webinar. 
          </Text>
        </Box>
        <Box as="div" py={["40px", "74px", "108px", "142px"]} px="36px">
          <Text fontWeight="600" textAlign="center" fontSize={["15px", "24px", "32px", "40px"]} color="black" maxW="1180px" className={styles.text}>
            <Text color="blue" display="inline">Ben Miller</Text> and <Text color="green" display="inline">Tiffany Joy Base</Text> are both passionate about financial empowerment and offer a wide variety of wit and wisdom that will be sure to delight you.
          </Text>
        </Box>
        <Box as="div" padding="80px 120px" className={styles.introduce}>
          <Flex className={styles.founder}>
            <Box as="div" className={styles.founderintro}>
              <Text fontWeight="400" textAlign="right" maxW="618px" className={styles.introducetext1}>
                <Text color="blue" display="inline">Ben Miller is the CEO and Founder of ChroniFI </Text> and has worked in finance for eight years and wants to bring financial education and tools to the masses.
              </Text>
            </Box>
            <Box as="div" px="56px">
              <Image src="/ben.png" alt="ben" width="420px" height="420px" />
            </Box>
          </Flex>
          <Flex justifyContent="center" alignItems="center" className={styles.personality}>
            <Box as="div" px="56px">
              <Image src="/Repeat_Grid_1.png" alt="ben" width="420px" height="420px" />
            </Box>
            <Box as="div" height="234px" padding="32px 72px" borderLeft="3px solid #54C577">
              <Text fontWeight="400" textAlign="left" maxW="560px" className={styles.introducetext2}>
                <Text color="green" display="inline">Tiffany is a former personal finance TV and Radio personality </Text> and author that has educated millions of women (and many men too).
              </Text>
            </Box>
          </Flex>
        </Box>
        <Box as="div" marginTop={["40px", "60px", "80px", "90px"]} padding="160px auto" width="100%">
          <Text className={styles.titletext} fontSize={["25px", "47px", "68px", "90px"]} textAlign="center" mx="auto" color="black">
            GET <Text color="blue" display="inline">FREE</Text> ACCESS
          </Text>
          <Flex mt={["10px", "12px", "14px", "16px"]} mb="20" className={styles.form}>
            <Box as="div" px="20px">
              <Text fontWeight="600" textAlign="left" fontSize={["15px", "20px", "25px", "30px"]} maxW="460px" color="black" className={styles.text}>
                To our Monthly Financial Freedom Webinars. <Text color="blue" display="inline">($88 value)</Text> Just sign up for our Personal Finance Newsletters and select one (or all) of our upcoming Webinar dates.
              </Text>
              <Text mt="5" fontWeight="200" textAlign="left" fontSize="18px" color="black" className={styles.text}>
                (We only email you personal finance content.)
              </Text>
              <Text mt="10" fontWeight="400" textAlign="left" fontSize={["15px", "17px", "20px", "22px"]} color="black" className={styles.text}>
                Pick your live webinar date:
              </Text>
              <Flex mt="2" flexDirection="column" justifyContent="center" alignItems="center">
                <Button
                  size="md"
                  mt="2"
                  color="white"
                  height="70px"
                  width={["100%", "100%", "100%", "464px"]}
                  rounded="16px"
                  backgroundColor="#54C577"
                >
                  June 21st 5 pm PDT
                </Button>
                <Button
                  size="md"
                  mt="2"
                  color="white"
                  height="70px"
                  width={["100%", "100%", "100%", "464px"]}
                  rounded="16px"
                  backgroundColor="#54C577"
                >
                  June 23rd 12 pm PDT
                </Button>
                <Button
                  size="md"
                  mt="2"
                  color="white"
                  height="70px"
                  width={["100%", "100%", "100%", "464px"]}
                  rounded="16px"
                  backgroundColor="#54C577"
                >
                  June 19th 5 pm PDT
                </Button>
                <Button
                  size="md"
                  mt="2"
                  color="white"
                  height="70px"
                  width={["100%", "100%", "100%", "464px"]}
                  rounded="16px"
                  backgroundColor="#54C577"
                >
                  June 21st 12 pm PDT
                </Button>
              </Flex>
            </Box>
            <Box as="div" className={styles.signup}>
              <Text fontWeight="600" color="black" fontSize={["15px", "20px", "25px", "30px"]} textAlign="center" className={styles.text}>
                Webinar Signup
              </Text>
              <Input borderRadius="12px" height="70px" mt="12" placeholder="Name" />
              <Input borderRadius="12px" height="70px" mt="4" placeholder="Email" />
              <Input borderRadius="12px" height="70px" mt="4" placeholder="Age" />
              <Input borderRadius="12px" height="70px" mt="4" placeholder="Zipcode" />
              <Button
                size="md"
                mt="8"
                color="white"
                height="70px"
                width="100%"
                rounded="16px"
                backgroundColor="#42A2DA"
              >
                Submit
              </Button>
            </Box>
          </Flex>
        </Box>
        <Flex width='100%'>
          {/* <Image src="/image.png" alt="ben" width="960px" height="740px" className={styles.healthimage} /> */}
          <Box as="div" width="100%" backgroundColor="#F5F5F5" padding={["40px", "74px", "108px", "142px"]}>
            <Text className={styles.healthtext1}>
              Want to have a little fun and see where you stand from a financial health perspective?
            </Text>
            <Text mt="70" className={styles.healthtext2}>
              Take our Financial Health Quiz and get your results immediately
            </Text>
            <Button
              size="md"
              marginTop="60px"
              color="white"
              height="70px"
              width="236px"
              rounded="16px"
              backgroundColor="#42A2DA"
            >
              Take the Quiz
            </Button>
          </Box>
        </Flex>
        <Box as="div" flexDirection="column" width="100%">
          <Flex py={["20px", "40px", "60px", "80px"]} className={styles.about}>
            <Box as="div" padding="24px">
              <Text fontWeight="600" fontSize={["20px", "38px", "54px", "74px"]} className={styles.text}>
                About <Text color="blue" display="inline" className={styles.text}>ChroniFI</Text>
              </Text>
              <Text mt="30px" fontWeight="300" fontSize={["14px", "21px", "28px", "35px"]} maxW="580px" className={styles.text}>
                At ChroniFI, we care about your financial future and are rooting for you to live the life of your dreams. To help you plan and reach your goals, we offer you a toolkit to assess your financial picture and play around with a variety of what-if scenarios to empower your life choices.
              </Text>
            </Box>
            <Box as="div" className={styles.phone}>
              <Image src="/phone.png" alt="ben" width="536px" height="570px" />
            </Box>
          </Flex>
          <Flex py={["20px", "40px", "60px", "80px"]} flexDirection="column" alignItems="center" backgroundColor="#556EBF">
            <Text fontWeight="400" padding="24px" fontSize={["15px", "24px", "33px", "42px"]} maxW="976px" className={styles.text} textAlign="center">
              Sign up for ChroniFI <Text color="green" display="inline" className={styles.text}>free</Text> today and let us guide you to a more joyful existence.
            </Text>
            <Button
              size="md"
              marginTop="60px"
              color="white"
              height="70px"
              width="236px"
              rounded="16px"
              backgroundColor="#54C577"
            >
              Sing Up
            </Button>
          </Flex>
        </Box>
      </main>
    </div>
  )
}
